"""update token table

Revision ID: 2a49a63ef88c
Revises: 7fccc21a79b9
Create Date: 2018-11-28 00:26:20.070008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a49a63ef88c'
down_revision = '7fccc21a79b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('token', 'user_id')
    # ### end Alembic commands ###
