"""bullet table

Revision ID: bd93d7d47b69
Revises: ac6edec313b1
Create Date: 2018-11-29 00:16:52.648870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd93d7d47b69'
down_revision = 'ac6edec313b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bullet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bullet_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bullet_timestamp'), 'bullet', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bullet_timestamp'), table_name='bullet')
    op.drop_table('bullet')
    # ### end Alembic commands ###
